version: "3.10"

services:
  javaapp:
    container_name: javaapp
    build: .
    ports:
      - "8000:8000"
    environment:
      - PG_USER=postgres
      - PG_PASSWORD=postgres
      - PG_DB=postgres-java
      - PG_PORT=5432
      - PG_HOST=java_db
    depends_on:
      - java_db

  java_db:
    container_name: java_db
    image: postgres:12
    environment:
      - POSTGRES_DB=postgres-java
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: {}
